version: '3.1'
services:
  app:
    container_name: servidor_apache_php
    image: servidor_apache_php:latest
    restart: always
    environment:
      DB_HOST: db
      DB_USER: user1
      DB_PASS: 123456
      DB_NAME: usuarios
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    container_name: servidor_mysql_mariadb
    image: josedom24/mibd
    restart: always
    environment:
      MARIADB_DATABASE: usuarios
      MARIADB_USER: user1
      MARIADB_PASSWORD: 123456
      MARIADB_ROOT_PASSWORD: 123456
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
    mariadb_data: