version: "3.9"

services:
  app:
    build: .
    container_name: servidor_apache_php
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: retrogaming_hub
      DB_USER: userphp
      DB_PASS: 123456
    depends_on:
      - db
    volumes:
      - .:/var/www/html:Z
  db:
    image: docker.io/library/mysql:latest
    container_name: servidor_mysql_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: usuarios
      MYSQL_USER: userphp
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  db_data:
      
